sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t youssefh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run youssefh/react-test npm test -- --coverage

after_success:
  - docker build -t youssefh/multi-client ./client
  - docker build -t youssefh/multi-nginx ./nginx
  - docker build -t youssefh/multi-server ./server
  - docker build -t youssefh/multi-worker ./worker
  # log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" 
  # push images
  - docker push youssefh/multi-client
  - docker push youssefh/multi-nginx
  - docker push youssefh/multi-server
  - docker push youssefh/multi-worker
